fileserver_backend:
  - gitfs

gitfs_provider: pygit2

gitfs_remotes:
  - git@github.com:tristankretzer/infra-salt.git:
    - root: salt
    - privkey: /etc/salt/pki/master/ssh/salt
    - pubkey: /etc/salt/pki/master/ssh/salt.pub

ext_pillar:
  - git:
    - master git@github.com:tristankretzer/infra-salt-pillar.git:
      - root: pillar
      - privkey: /etc/salt/pki/master/ssh/pillar
      - pubkey: /etc/salt/pki/master/ssh/pillar.pub

sops_args: --output-type=yaml --input-type=yaml -d /dev/stdin

sops_env:
  SOPS_AGE_KEY_FILE: /etc/salt/pki/master/age/key.txt
